version: 2.1
setup: true

orbs:
  orb-tools: circleci/orb-tools@11.1

filters: &filters
  tags:
    only: /.*/

jobs:
  python-tests:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - run:
          name: Install package
          command: python -m pip install -e .
      - run:
          name: Run unit tests
          command: python -m unittest discover -s tests -v
      - run:
          name: CLI smoke test
          command: orb-lint tests/fixtures/orb001/pass

workflows:
  phase-1-2:
    jobs:
      - python-tests:
          filters: *filters
      - orb-tools/lint:
          filters: *filters
      - orb-tools/review:
          exclude: RC006
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: orbss/orb-lint
          vcs-type: << pipeline.project.type >>
          pub-type: dev
          enable-pr-comment: false
          context: CIRCLECI_ORBS
          requires:
            - python-tests
            - orb-tools/lint
            - orb-tools/review
            - orb-tools/pack
          filters: *filters
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          requires:
            - orb-tools/publish
          filters: *filters
